CREATE DATABASE `prontvet`;

USE `prontvet`;

CREATE TABLE IF NOT EXISTS `pacientes` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`nome` VARCHAR(255) NOT NULL,
	`raca` VARCHAR(255) NOT NULL,
	`sexo` CHAR NOT NULL,
	`idade` INT NOT NULL,
	`peso` DOUBLE NOT NULL
)

CREATE TABLE IF NOT EXISTS `tutores` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`nome` VARCHAR(255) NOT NULL,
	`telefone` VARCHAR(255) NOT NULL,
	`endereco` VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS `usuarios` (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`email` VARCHAR(255) NOT NULL,
	`senha` VARCHAR(255) NOT NULL
)
